export const ADD_JOURNAL = 'ADD_JOURNAL';
export const EDIT_JOURNAL = 'UPDATE_JOURNAL';
export const DELETE_JOURNALS = 'DELETE JOURNALS';
export const DELETE_JOURNAL = 'DELETE JOURNAL';

export const RECEIVE_JOURNALS = 'RECEIVE_JOURNALS';
export const FETCH_ALL_JOURNALS = 'FETCH_ALL_JOURNALS';

export const ADD_ENTRY = 'ADD_ENTRY';
export const EDIT_ENTRY = 'EDIT_ENTRY';
export const DELETE_ENTRY = 'DELETE_ENTRY';
export const DELETE_ENTRIES = 'DELETE_ENTRIES';

export const RECEIVE_ENTRIES = 'RECEIVE_ENTRIES';
export const FETCH_ALL_ENTRIES = 'FETCH_ALL_ENTRIES';
